services:
    broker:
      image: eclipse-mosquitto
      container_name: mqtt5
      ports:
          - "1883:1883" #default mqtt port
          - "9001:9001" #default mqtt port for websockets
      volumes:
        - /home/bstill/mqttInflux/mqtt/config:/mosquitto/config:rw
        - /home/bstill/mqttInflux/mqtt/data:/mosquitto/data:rw
        - /home/bstill/mqttInflux/mqtt/log:/mosquitto/log:rw
      restart: unless-stopped

      # volumes for mapping data,config and log



    server:
      image: server
      environment:
        MQTT_HOST: "mqtt5"
        MQTT_PORT: "1883"
        MQTT_USER: "delta"
        MQTT_PASSWORD:  "KeepClimbing!"
      volumes:
        - /home/bstill/logs:/logs
      networks:
        - outside
      restart: unless-stopped



volumes:
   data:
   config:
   log:
   logdir:

